//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СамостоятельнаяLis1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pynkt_vidachi
    {
        public int hIndex { get; set; }
        public string City_1 { get; set; }
        public string Street { get; set; }
        public Nullable<int> House { get; set; }
    }
}
