//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СамостоятельнаяLis1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazi2
    {
        public int Nomer_Zakaza { get; set; }
        public string Sostav_zakaza { get; set; }
        public string Date_zakaza { get; set; }
        public string Date_dostavki { get; set; }
        public int pynkt_vidachi1 { get; set; }
        public string Full_name { get; set; }
        public int Kod_polychenia { get; set; }
        public string Status_zakaza { get; set; }
        public string City { get; set; }
    }
}
